language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0

cache: bundler
bundler_args: --path ../../vendor/bundle
gemfile:
  - spec/gemfiles/rails_4_0.gemfile
  - spec/gemfiles/rails_4_1.gemfile
  - spec/gemfiles/rails_4_2.gemfile

env:
  - DB=postgresql
  - DB=mysql2

sudo: false

before_script: "RAILS_ENV=test bundle exec rake db:create db:migrate"

script: "bundle exec rake"

notifications:
  slack:
    secure: bnoj7Q/2yA3gtJ2IR/YtXrWCGvN7ukHKnhg1oNYJsOYNk0oEMMgjmGnIRrcdxO4peyOid6aKlcMmP7zrOzPEJsN3qAA4UUCRGq0TgZ2RDMX1sRZ8NN/xCyt84WU9aEtTF0V1hUyG/OaQ7G65XN/XuwJGzw6VDSZE54FSdR/5/eQ=
