language: ruby

rvm:
  - 2.0.0
  - 2.1.0

gemfile:
  - spec/gemfiles/rails_4_0.gemfile
  - spec/gemfiles/rails_4_1.gemfile
  - spec/gemfiles/rails_4_2.gemfile

env:
  - DB=postgresql
  - DB=mysql2

sudo: false

before_script: "RAILS_ENV=test bundle exec rake db:create db:migrate"

script: "bundle exec rake"
