<%
db_adapter = ENV.fetch('DB', 'sqlite3')
db_host    = ENV.fetch('DB_HOST', ENV.fetch('THREDDED_DB_1_PORT_5432_TCP_ADDR', 'localhost'))
db_port    = ENV['DB_PORT'] || ENV['THREDDED_DB_1_PORT_5432_TCP_ADDR'] ||
  {'postgresql' => 5432, 'mysql2' => 3306}[db_adapter]
%>

defaults: &defaults
  host: <%= db_host %>
  port: <%= db_port %>
  adapter: <%= db_adapter %>
  encoding: utf8
  min_messages: WARNING
  username: <%= ENV.fetch('DB_USERNAME', 'thredded').inspect %>
  password: <%= ENV.fetch('DB_PASSWORD', 'thredded').inspect %>

development:
  <<: *defaults
  database: <%= db_adapter == 'sqlite3' ? 'db/development.sqlite3' : 'thredded_gem_dev' %>

test:
  <<: *defaults
  database: <%= db_adapter == 'sqlite3' ? "':memory:'" : 'thredded_gem_test' %>
