defaults: &defaults
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: utf8
  min_messages: WARNING
  pool: 5
  username: "postgres"
  password: 

development:
  <<: *defaults
  database: thredded_dev

test:
  <<: *defaults
  database: thredded_test

