defaults: &defaults
  host: <%= ENV.fetch('THREDDED_DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('THREDDED_DB_1_PORT_5432_TCP_PORT', 5432) %>
  adapter: <%= ENV.fetch('DB', 'postgresql') %>
  encoding: utf8
  min_messages: WARNING
  username: <%= ENV.fetch('DB_USERNAME', 'thredded').inspect %>
  password: <%= ENV.fetch('DB_PASSWORD', 'thredded').inspect %>

development:
  <<: *defaults
  database: thredded_gem_dev

test:
  <<: *defaults
  database: thredded_gem_test
