defaults: &defaults
  host: localhost
  adapter: postgresql
  encoding: UTF8
  min_messages: WARNING

development:
  <<: *defaults
  host: localhost
  database: thredded_gem_dev

test:
  <<: *defaults
  host: localhost
  database: thredded_gem_test
